config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  root 'home#index'
  get 'download_resume', to: "home#download_resume"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :projects
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def download_resume
    send_file "#{Rails.root}/app/assets/docs/Evan Pavone - Resume.pdf", type: "application/pdf", x_sendfile: true
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @project = current_user.projects.find_by(id: params[:id])
    redirect_to projects_path, notice: "Not Authorized" if @project.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:project_name, :github, :description, :language, :video_demo, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <%= link_to 'Evan Pavone', root_path, class: "navbar-brand"%>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to "Projects", projects_path, class: "nav-link"%>
                </li>
                <% if user_signed_in? %>
                    <% if current_user.email == "evanrpavone@gmail.com" %>
                        <li class="nav-item">
                            <%= link_to 'Add Project', new_project_path, class: "nav-link"%>
                        </li>
                    <% end %>
                <li class="nav-item">
                    <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete, class: "nav-link"%>
                </li>
                <% else %>
                <li class="nav-item">
                    <%= link_to 'Login', new_user_session_path, class: "nav-link"%>
                </li>
                <% end%>
                <li class="nav-item">
                    <small class="text-muted">v1.0</small>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/home/index.html.erb
<div class="card">
  <div class="card-header">
    <h1 class="card-title">Evan Pavone's Portfolio</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">About Me</h5>
    <p class="card-text">Leveraging my experience in the fast-food industry, along with a decade of volunteer work in Costa Rica. I am agile, resourceful, timely and organized. I am an up-and-coming software developer who is passionate about coding. I am experienced in Ruby on Rails, JavaScript-based programming, HTML and CSS</p>
    <%= link_to "Projects", projects_path, class: "btn btn-success"%>
    <br/>
    <br/>
    <h5 class="card-title">Technical Skills</h5>
    <small class="text-muted">Ordered from strongest to weakest</small>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Ruby on Rails</li>
      <li class="list-group-item">JavaScript</li>
      <li class="list-group-item">Photoshop</li>
      <li class="list-group-item">React</li>
      <li class="list-group-item">HTML/CSS</li>
      <li class="list-group-item">Command Line Interface (CLI)</li>
    </ul>
    <br/>
    <h5 class="card-title">Soft Skills</h5>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Agility</li>
      <li class="list-group-item">Resourcefulness</li>
      <li class="list-group-item">Timeliness</li>
      <li class="list-group-item">Organizational Skills</li>
      <li class="list-group-item">Problem Solving</li>
    </ul>
    <br/>
    <h5 class="card-title">Hobbies</h5>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Video Games</li>
      <li class="list-group-item">Hiking</li>
      <li class="list-group-item">Brewery Hopping</li>
      <li class="list-group-item">Walking My Dog Joey</li>
    </ul>
  </div>
</div>
<br/>
<div class="card text-center">
  <div class="card-header">
    <h5 class="card-title">My Links</h5>
  </div>
  <div class="card-body">
    <%= link_to 'Github', "https://github.com/EvanRPavone", class: "btn btn-success", target: "_blank" %>
    <%= link_to 'LinkedIn', "https://www.linkedin.com/in/evan-pavone/", class: "btn btn-primary", target: "_blank" %>
    <%= link_to 'Blog', "https://dev.to/evanrpavone", class: "btn btn-danger", target: "_blank" %>
    <%= link_to "Download Resumé", download_resume_path, class:"btn btn-warning", target: "_blank"%>
    <a href="/images/myw3schoolsimage.jpg" download>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Evan Pavone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "home/header" %>
    <div class="container">
    <br/>
      <% if notice %>
        <%= render "layouts/alerts" %>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

  </body>
</html>

app/views/projects/_form.html.erb
<% if user_signed_in? %>
  <% if current_user.email == "evanrpavone@gmail.com" %>
    <%= form_with(model: project) do |form| %>
      <% if project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% project.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="card">
        <div class="card-header">
          Project Form
        </div>
        <div class="card-body">
          <%= form.label :project_name, class:"form-label" %>
          <%= form.text_field :project_name, class:"form-control"%>

          <%= form.label :github, class:"form-label" %>
          <%= form.text_field :github, class:"form-control" %>

          <%= form.label :description, class:"form-label" %>
          <%= form.text_area :description, class:"form-control", rows:"3" %>

          <%= form.label :language, class:"form-label"%>
          <%= form.text_field :language, class:"form-control" %>

          <%= form.label :video_demo, class:"form-label" %>
          <%= form.text_field :video_demo, class:"form-control" %>
          
          <%= form.number_field :user_id, id: :project_user_id, class: "form-control", value: current_user.id, type: :hidden %>
          <br/>
          <%= form.submit class:"btn btn-success"%>
    <% end %>
    <% else %>
    <p>You are not Evan, Sorry!</p>
        </div>
      </div>
  <% end %>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="card">
  <div class="card-header">
    <h1 class="card-title">My Projects</h1>
    <% if user_signed_in? %>
      <% if current_user.email == "evanrpavone@gmail.com" %>
        <%= link_to 'New Project', new_project_path, class:"btn btn-secondary" %>
      <% end %>
    <% end %>
  </div>
  <div class="card-body">
    <% @projects.each do |project| %>
    <div class="card" style="width: 16rem; float: left; margin: 20px;">
      <iframe src= <%= project.video_demo %> class="card-img-top" title=<%= project.project_name %> frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <div class="card-body">
        <h5 class="card-title"><%= project.project_name %></h5>
        <p class="card-text"><%= project.description %></p>
        <%= link_to 'Github', project.github, class: "btn btn-secondary" %>
        <%= link_to 'Show Project', project, class: "btn btn-secondary" %>
      </div>
      <div class="card-footer">
        <small class="text-muted"><%= project.language %></small>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="card">
  <div class="card-header text-center">
    <h1 class="card-title"><%= @project.project_name %></h1>
  </div>
  <div class="card-body">
    <div class="embed-responsive embed-responsive-16by9 text-center">
      <iframe width="560" height="315" src= <%= @project.video_demo %> title=<%= @project.project_name %> frameborder="0" allowfullscreen></iframe> 
    </div> 
    <p class="card-text" style="padding: 30px;"><strong>Description:</strong><br/><%= @project.description %></p>
    <p class="card-text text-center"><%= link_to 'Github', @project.github, class: "btn btn-secondary" %></p>
  </div>
  <div class="card-footer text-muted text-center">
    <%= @project.language %>
  </div>
</div>
<br/>
<% if user_signed_in? %>
  <% if current_user.email == "evanrpavone@gmail.com" %>
    <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-primary" %> |
  <% end %>
<% end %>
<%= link_to 'Back', projects_path, class: "btn btn-secondary" %>